create table command_task (
    id bigint not null auto_increment,
    task_uuid varchar(64) not null,
    message_type varchar(64) not null,
    brand varchar(32),
    shop_code varchar(64),
    ap_code varchar(64),
    tag_id varchar(64),
    vendor_task_id bigint,
    status varchar(32) not null,
    allow_replay bit not null default b'0',
    mqtt_topic varchar(255),
    mqtt_payload longtext,
    raw_message longtext,
    error_message text,
    queued_at timestamp(6) null,
    published_at timestamp(6) null,
    ap_acked_at timestamp(6) null,
    esl_reported_at timestamp(6) null,
    success_at timestamp(6) null,
    failed_at timestamp(6) null,
    timeout_at timestamp(6) null,
    deadline_at timestamp(6) null,
    version bigint not null,
    created_at timestamp(6) not null,
    updated_at timestamp(6) not null,
    primary key (id),
    unique key uk_command_task_uuid (task_uuid),
    key idx_command_task_status_deadline (status, deadline_at),
    key idx_command_task_tag_status (tag_id, status),
    key idx_command_task_type (message_type)
) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_unicode_ci;

create table ap_device (
    id bigint not null auto_increment,
    ap_code varchar(64) not null,
    client_id varchar(128),
    shop_code varchar(64),
    shop_id bigint,
    shop_no int,
    online bit not null default b'0',
    last_heartbeat_at timestamp(6) null,
    heartbeat_index bigint,
    cpu_usage double,
    memory_usage double,
    disk_usage double,
    ip_address varchar(64),
    mac_address varchar(64),
    firmware_version varchar(128),
    app_version varchar(128),
    last_payload longtext,
    created_at timestamp(6) not null,
    updated_at timestamp(6) not null,
    primary key (id),
    unique key uk_ap_device_code (ap_code),
    key idx_ap_device_shop (shop_code)
) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_unicode_ci;

create table esl_tag (
    id bigint not null auto_increment,
    tag_id varchar(64) not null,
    ap_code varchar(64),
    shop_code varchar(64),
    battery_soc int,
    ssirs int,
    temperature decimal(10, 2),
    stat_raw varchar(64),
    last_report_at timestamp(6) null,
    last_payload longtext,
    created_at timestamp(6) not null,
    updated_at timestamp(6) not null,
    primary key (id),
    unique key uk_esl_tag_id (tag_id),
    key idx_esl_tag_ap (ap_code),
    key idx_esl_tag_shop (shop_code)
) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_unicode_ci;

create table tag_key (
    id bigint not null auto_increment,
    tag_id varchar(64) not null,
    shop_code varchar(64),
    ap_code varchar(64),
    sk varchar(128) not null,
    tk varchar(128) not null,
    created_at timestamp(6) not null,
    updated_at timestamp(6) not null,
    primary key (id),
    unique key uk_tag_key_tag (tag_id),
    key idx_tag_key_shop (shop_code)
) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_unicode_ci;

create table command_event_log (
    id bigint not null auto_increment,
    task_uuid varchar(64),
    event_type varchar(64) not null,
    status_from varchar(32),
    status_to varchar(32),
    topic varchar(255),
    payload longtext,
    message text,
    error text,
    created_at timestamp(6) not null,
    primary key (id),
    key idx_command_event_task (task_uuid),
    key idx_command_event_type (event_type),
    key idx_command_event_created (created_at)
) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_unicode_ci;
